context.modules = [
	{ name = libpipewire-module-filter-chain
		args = {
			node.description = "Background noise gone Mic"
			media.name       = "Background noise gone Mic"
			filter.graph = {
				nodes = [
					#{ type = ladspa name = rnnoise plugin = "/usr/lib64/ladspa/librnnoise_ladspa.so" label = noise_suppressor_mono control = { "VAD Threshold (%)" = 99 "VAD Grace Period (ms)" = 200 "Retroactive VAD Grace (ms)" = 0 } }

					{ type = ladspa name = "DeepFilter Mono" plugin = "/usr/lib64/ladspa/libdeep_filter_ladspa.so" label = deep_filter_mono control = { "Attenuation Limit (dB)" 100 } }
					#{ type = ladspa name = "DeepFilter Mono" plugin = "/usr/lib64/ladspa/libdeep_filter_ladspa.so" label = deep_filter_mono control = { "Attenuation Limit (dB)" 80 "Min processing threshold (dB)" -15 "Max ERB processing threshold (dB)" 35 "Max DF processing threshold (dB)" 35 "Min Processing Buffer (frames)" 10 "Post Filter Beta" 0.05 } }
					{ type = lv2 name = gate_mono plugin = "http://lsp-plug.in/plugins/lv2/gate_mono" control = { g_in 15 scm = 1 shpm = 1 shpf = 80.0 gt = 0.02 at = 5.0 rt = 300.0 gr = 0.0003 } }
					{ type = lv2 name = compressor_mono plugin = "http://lsp-plug.in/plugins/lv2/compressor_mono" control = {  cr = 4.0 al = 0.316 at = 10.0 rt = 60 mk = 1 } }
					{ type = lv2 name = limiter_mono plugin = "http://lsp-plug.in/plugins/lv2/limiter_mono" control = { th = 0.891 rt = 60 } }
				]
				links = [
					{ output = "DeepFilter Mono:Audio Out" input = "gate_mono:in" }
					#{ output = "rnnoise:Output" input = "compressor_mono:in" }
					{ output = "gate_mono:out" input = "compressor_mono:in" }
					#{ output = "DeepFilter Mono:Audio Out" input = "compressor_mono:in" }
					{ output = "compressor_mono:out" input = "limiter_mono:in" }
				]
			}
			capture.props = {
				node.name = "Background noise gone In"
				#target.object = "alsa_input.usb-MOTU_M2_M2MT15C48F-00.HiFi__Mic1__source"
				target.object = "alsa_input.usb-MOTU_M2_M2MT15C48F-00.pro-input-0"
				node.passive = true
				audio.position = [ MONO ]
			}
			playback.props = {
				node.name = "Background noise gone Out"
				audio.position = [ MONO ]
				media.class = Audio/Source
			}
		}
	}
]
