#lavfi-complex=[aid1][aid2][aid3]amix=inputs=3[ao]
audio-pitch-correction=yes
alang=en
expected_sub_words=SDH
force-seekable=yes
force-window=yes
gpu-api=vulkan
hwdec=nvdec
#interpolation=yes
keep-open=yes
profile=high-quality
save-position-on-quit=yes
save-watch-history=yes
screenshot-directory=/home/justcausewhynot/Pictures/mpv
screenshot-format=png
screenshot-png-compression=0
slang=en
#tscale=oversample
video-sync=audio
vo=gpu-next
