#!/bin/sh

# Loads scripts in ~/xinitrc.d.
# =============================
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Start programs.
# ===============
#xrdb -load ~/.config/X11/xresources &
#easyeffects --gapplication-service &
playerctld daemon &
xrandr --output DP-2 --set CscMatrix 66110,-2311,1736,0,-56,64309,1282,0,407,3322,61805,0 &
xbanish -i modifier -s &
#gentoo-pipewire-launcher &
#xboxdrv --type xbox360 --device-by-id 31e3:1300 --silent --quiet --detach-kernel-driver --mimic-xpad &
nvidia-settings -l &
exec dbus-launch --exit-with-session /usr/local/bin/dwm
