#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Loads scripts in ~/xinitrc.d.
# =============================
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Start programs.
# ===============
playerctld daemon &
numlockx on &
xrandr --output DP-2 --set CscMatrix 66110,-2311,1736,0,-56,64309,1282,0,407,3322,61805,0 &
xbanish -i modifier -s &
nvidia-settings -l &
xrdb -load ~/.config/X11/xresources
gentoo-pipewire-launcher &
doas nvidia-settings -a "[gpu:0]/GPUFanControlState=1" -a "[fan:0]/GPUTargetFanSpeed=100" &
doas nvidia-smi -pl 132 &
exec dbus-launch --exit-with-session /usr/local/bin/dwm
#exec /usr/local/bin/dwm
