#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Loads scripts in ~/xinitrc.d.
# =============================
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Start programs.
# ===============
playerctld daemon &
numlockx on &
#xbanish -i modifier -s &
xrdb -load ~/.config/X11/xresources &
openrgb -p disabled.orp &
gentoo-pipewire-launcher &
doas nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings -l &
doas nvidia-settings -a "GPUFanControlState=1" -a "GPUTargetFanSpeed=100" &
doas nvidia-smi -pl 253 &
exec dbus-launch --exit-with-session /usr/local/bin/dwm
