#!/bin/sh

GAME_DIR=`dirname "$(realpath "$0")"`

export LD_LIBRARY_PATH="$GAME_DIR":"$LD_LIBRARY_PATH"
__GL_THREADED_OPTIMIZATION=1 MANGOHUD_CONFIG=read_cfg,position=bottom-right,offset_x=-80,offset_y=-140 mangohud gamemoderun sh ./cream.sh "$GAME_DIR/hoi4" "$@"
