#!/bin/sh
#efibootmgr -b 0 -B & efibootmgr -b 1 -B & efibootmgr -b 8 -B
#efibootmgr -c -d /dev/nvme1n1 -p 1 -L "Gentoo" -l '\efi\EFI\Gentoo\vmlinuz-6.9.3-gentoo.efi' -u 'root=PARTUUID=290c7256-80f7-41fb-b844-10641c661382 mitigations=off'
efibootmgr -c -d /dev/nvme1n1 -p 1 -L "Gentoo" -l '\efi\EFI\Gentoo\bzImage.efi' -u 'root=PARTUUID=290c7256-80f7-41fb-b844-10641c661382 mitigations=off'
#efibootmgr -c -d /dev/nvme0n1 -p 1 -L "Memtest86+" -l '\efi\memtest\memtest.efi64' -u 'keyboard=usb usbdebug usbinit=1'
